name: Node CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # Build/lint the codebase, making the compiled code available as an artifact
  # TODO: add testing
  build_and_lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    # TODO set node_env to production but also force yarn to install dev dependencies
    # env:
    #   NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile

      # Lint source code
      - name: Lint
        run: yarn lint

      # Compile the source code
      - name: Build
        run: yarn build

      # Make the build code downloadable
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cmsc435-discord-bot
          path: dist/**
          retention-days: 1

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      WEBHOOK_URL: https://discord.com/api/webhooks/800453941313745987/foo-bar-baz-bang

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Install dependencies
      - name: Install
        run: yarn install --frozen-lockfile

      # Lint source code
      - name: Test
        run: yarn test

      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: path/**
          retention-days: 1
